spring:
  application:
    name: microservice-web-news
  zipkin:
    base-url: http://localhost:9411
  # common web
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

feign:
  hystrix:
    enabled: true


server:
  port: 8602

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hosts:
  sso: http://localhost:8503

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info