spring:
  application:
    name: microservice-service-news
  zipkin:
    base-url: http://localhost:9411
  datasource:
    druid:
      url: jdbc:mysql://139.224.117.172:3306/forum?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 139.224.117.172:26379, 139.224.117.172:26380, 139.224.117.172:26381

feign:
  hystrix:
    enabled: true

# common service
mybatis:
  configuration:
    cache-enabled: true
  type-aliases-package: org.caps.microservice.common.domain
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8504

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info